POST  http://localhost:3000/api/produtos
Content-Type: application/json
    {
      "name": "Kinganda BT513 Foldable Bluetooth Headphones With Mic",
      "images": [
        "https://i.ibb.co/qs8yhPB/headphone.jpg",
        "https://i.ibb.co/m6ZN7LX/soundBox.webp",
        "https://i.ibb.co/wdV3b9q/vaccum.webp",
        "https://i.ibb.co/tcdSfrr/blueGun.jpg",
        "https://i.ibb.co/pw0fGmx/gaming-Controller.webp"
      ],
      "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
      "regularPrice": 600,
      "discountedPrice": 550,
      "quantity": 1,
      "rating": 4,
      "reviews": 60,
      "category": "Headphones & Speakers",
      "colors": [
        "red",
        "blue",
        "green",
        "yellow",
        "black",
        "white"
      ],
      "brand": "Lorem ipsum dolor sit",
      "isStock": true,
      "overView": "Microphones",
      "isNew": true
    }
###

GET http://localhost:3008/api/produtos

###

GET http://localhost:3008/api/produtos/66c76e3f16e00c5c21522e7b

###

DELETE http://localhost:3008/api/produtos/66e09f12c9fb6d0ca6d1f29d


###

PUT  http://localhost:3008/api/categorias/66e049d09d98b7c9cf879726
Content-Type: application/json

  {
    "name": "Cameras & Photos",
    "image": "https://i.ibb.co/SVQVWSS/cat-Camera.webp",
    "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.",
    "_base": "camerasAndPhotos"
  }

###


POST  http://localhost:3000/api/vendedor
Content-Type: application/json

{
  "nome": "Luuuu Lima",
  "codigo":4,
  "rua": "Pres Bernardes",
  "numero": 1584,
  "cidade": "Cascavel",
  "imagem": "https://www.google.com/url?sa=i&url=https%3A%2F%2Fbr.freepik.com%2Ffotos-vetores-gratis%2Fmoletom-png&psig=AOvVaw3x3nhtcyEFttjuxO7NVLiW&ust=1724432225884000&source=images&cd=vfe&opi=89978449&ved=0CBEQjRxqFwoTCID9iOSIiYgDFQAAAAAdAAAAABAI",
  "observacao": "Pai do Dauran",
  "produtos": [
    {
      "nome": "Moletom Adidas",
      "codigo":3314,
      "descricao": "Descrição do produto 3",
      "categoria": "Moletom",
      "quantidade": 1,
      "preco":199.00,
      "tamanho": "G",
      "imagem": "https://www.google.com/url?sa=i&url=https%3A%2F%2Fbr.freepik.com%2Ffotos-vetores-gratis%2Fmoletom-png&psig=AOvVaw3x3nhtcyEFttjuxO7NVLiW&ust=1724432225884000&source=images&cd=vfe&opi=89978449&ved=0CBEQjRxqFwoTCID9iOSIiYgDFQAAAAAdAAAAABAI"
    }
  ]
}

###

GET http://localhost:3000/api/vendedor

###

GET http://localhost:3000/api/vendedor/66c89af006e77ae0a0409d02

###

DELETE http://localhost:3000/api/vendedor/66c89c12741eaef2e0fdc568


###

PUT  http://localhost:3000/api/vendedor/66c89af006e77ae0a0409d02
Content-Type: application/json

{
  "nome": "Reginaldo Geraldo",
  "codigo":1,
  "rua": "Nereu Ramos",
  "numero": 1875,
  "cidade": "Cascavel",
  "imagem": "https://www.google.com/url?sa=i&url=https%3A%2F%2Fbr.freepik.com%2Ffotos-vetores-gratis%2Fmoletom-png&psig=AOvVaw3x3nhtcyEFttjuxO7NVLiW&ust=1724432225884000&source=images&cd=vfe&opi=89978449&ved=0CBEQjRxqFwoTCID9iOSIiYgDFQAAAAAdAAAAABAI",
  "observacao": "cliente antigo e dono da empresa"
}